### ISSUE TITLE
i5 9600k 华硕B360M

### ISSUE THREAD

**Issue by Likeyong** [XY-e/HackintoshEFI#3]

**Comment by Likeyong** [comment]
i5 9600k 华硕B360M 可以用你的EFI吗

**Comment by XY-e** [comment]
> i5 9600k 华硕B360M 可以用你的EFI吗

@Likeyong  你看看这个：https://github.com/cc976655/MyBlackAppleEFI

**Comment by Likeyong** [comment]
> > i5 9600k 华硕B360M 可以用你的EFI吗
> 
> @Likeyong 你看看这个：https://github.com/cc976655/MyBlackAppleEFI

哈哈,感谢,我就是从那边转过来的
